function credentialPath = createcreds()
    credentialPath = [];
    credentials = inputdlg({'Configuration filename', ...
        'Database name', 'Host name', ...
        'Port number', 'User name', 'Password'}, ...
        'Database credentials', ...
        [1 40; 1 40; 1 40; 1 12; 1 40; 1 40], ...
        {'config.properties', 'ctagger', 'localhost', '5432', ...
        'postgres', 'password'}, 'on');
    if ~isempty(credentials)
        directory = uigetdir();
        if directory ~= 0
            credentialPath = [directory filesep credentials{1}];
            edu.utsa.tagger.database.TagsDBManager.createCredentials( ...
                credentialPath, credentials{2}, credentials{3},  ...
                credentials{4}, credentials{5}, credentials{6});
        end
    end
end % createcreds