%% Publish the documentation in this directory

%% Publish the function scripts top level
baseDirectory = pwd;
publish_options.outputDir = baseDirectory;
publish_options.maxHeight = 300;
coreScripts = { ...
              'findtags_help', ...
              'findtagsdir_help', ...             
              'tagdir_help', ...
              'tageeg_help', ...
              'tagstudy_help' ...
              };
          
for k = 1:length(coreScripts)
   publish([coreScripts{k} '.m'], publish_options);
end
close all
clear all

%% Publish the eventTags help
baseDirectory = pwd;
publish_options.outputDir = baseDirectory;
publish_options.maxHeight = 300;
coreScripts = { ...
              'eventTags_overview_help', ...
              'eventTags_addEvent_help', ...             
              'eventTags_get_methods_help', ...
              'eventTags_static_methods_help', ...
              'tagstudy_help' ...
              };
          
for k = 1:length(coreScripts)
   publish([coreScripts{k} '.m'], publish_options);
end
close all
clear all